on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsconfigureawscr-e5bsJYOBLbg1:7c24d3c1-c1fb-4c42-9ccc-dda1ffbe7aa6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@f3ce02b09489ff8e8b9a0befc5d81e68c8b8ce41
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Test environment is configured with AWS credentials
      run: |
        aws sts get-caller-identity --query Arn | grep "user/github-actions-configure-aws-credentials-integ-tests" > /dev/null

    - name: Configure AWS credentials from role
      uses: aws-actions/configure-aws-credentials@f3ce02b09489ff8e8b9a0befc5d81e68c8b8ce41
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        role-to-assume: github-actions-configure-aws-credentials-integ-tests
        role-duration-seconds: 900
        role-session-name: github-actions-integ-test
        role-external-id: ${{ secrets.INTEG_TEST_ROLE_EXTERNAL_ID }}

    - name: Test environment is configured with AWS credentials from role
      run: |
        aws sts get-caller-identity --query Arn | grep "role/github-actions-configure-aws-credentials-integ-tests"  > /dev/null

    - name: Configure AWS credentials from role again
      uses: aws-actions/configure-aws-credentials@f3ce02b09489ff8e8b9a0befc5d81e68c8b8ce41
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        role-to-assume: github-actions-configure-aws-credentials-integ-tests
        role-duration-seconds: 900
        role-session-name: github-actions-integ-test
        role-external-id: ${{ secrets.INTEG_TEST_ROLE_EXTERNAL_ID }}

    - name: Test environment is configured with AWS credentials from role
      run: |
        aws sts get-caller-identity --query Arn | grep "role/github-actions-configure-aws-credentials-integ-tests"  > /dev/null
